// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaeunckbuhtyuxnnpgtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZXVuY2tidWh0eXV4bm5wZ3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDkwMDUsImV4cCI6MjA2ODkyNTAwNX0.g7tskAJpFEOdDhqjrfB4pdMGRypSgFNsdtXdxfNqKyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});